<?php
require_once __DIR__.'/../includes/functions.php'; require_once __DIR__.'/../includes/auth.php'; require_once __DIR__.'/../includes/csrf.php'; require_once __DIR__.'/../includes/audit.php';
if($_SERVER['REQUEST_METHOD']==='GET'){ require_api_login(); $where=[];$p=[];if(!empty($_GET['status'])){$where[]='f.status=?';$p[]=$_GET['status'];}if(!empty($_GET['department'])){$where[]='f.department_id=?';$p[]=(int)$_GET['department'];}$sql='SELECT f.*,d.name department,c.name category,u.name assignee FROM anonymous_feedback f JOIN departments d ON d.id=f.department_id LEFT JOIN feedback_categories c ON c.id=f.category_id LEFT JOIN users u ON u.id=f.assigned_to'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY f.created_at DESC LIMIT 300';$s=db()->prepare($sql);$s->execute($p);json_response(['ok'=>true,'feedback'=>$s->fetchAll()]); }
$d=json_input(); require_csrf($d['csrf_token']??null); $action=$d['action']??'';
if($action==='submit'){$dept=(int)($d['department_id']??0);$text=trim($d['feedback_text']??'');if(!$dept||mb_strlen($text)<5)json_response(['ok'=>false,'message'=>'Please select a department and enter meaningful feedback.'],422);$sent='neutral';$lower=mb_strtolower($text);$positive=['great','good','excellent','happy','appreciate','helpful','love','improved'];$negative=['bad','poor','unsafe','harass','unfair','problem','toxic','terrible','complaint'];$ps=$ns=0;foreach($positive as $w)if(str_contains($lower,$w))$ps++;foreach($negative as $w)if(str_contains($lower,$w))$ns++;if($ps>$ns)$sent='positive';elseif($ns>$ps)$sent='negative';$s=db()->prepare('INSERT INTO anonymous_feedback(department_id,category_id,feedback_text,sentiment,ip_hash) VALUES(?,?,?,?,?)');$s->execute([$dept,(int)($d['category_id']??0)?:null,$text,$sent,request_ip_hash()]);json_response(['ok'=>true,'message'=>'Feedback submitted anonymously.']);}
require_api_login();
if($action==='status'){$id=(int)$d['id'];$status=$d['status']??'new';if(!in_array($status,['new','under_review','resolved','archived'],true))json_response(['ok'=>false],422);db()->prepare('UPDATE anonymous_feedback SET status=? WHERE id=?')->execute([$status,$id]);audit('status_update','feedback',$id,['status'=>$status]);json_response(['ok'=>true]);}
if($action==='note'){$id=(int)$d['id'];$note=trim($d['note']??'');if(!$note)json_response(['ok'=>false],422);db()->prepare('INSERT INTO feedback_notes(feedback_id,user_id,note) VALUES(?,?,?)')->execute([$id,current_user()['id'],$note]);audit('note','feedback',$id);json_response(['ok'=>true]);}
json_response(['ok'=>false,'message'=>'Unsupported action'],400);
